# Generated by Django 6.1 on 2026-09-27 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reparacion',
            name='estado',
            field=models.CharField(choices=[('INGRESADO', 'Ingresado'), ('DIAGNOSTICO', 'En diagnóstico'), ('REPARANDO', 'En reparación'), ('ESPERA', 'Esperando repuesto'), ('FINALIZADO', 'Finalizado'), ('ENTREGADO', 'Entregado'), ('SIN REPARACION', 'sin reparación')], default='INGRESADO', max_length=20),
        ),
    ]
